### PR TITLE
Update LICENSE.md

### PR DESCRIPTION
**Pull request by drkgry**

### CODE REVIEW

**Comment by turbolay** [comment]
This change is not OK. 

MIT license forces you to mention the original license owner. Because the intellectual property was transferred from `zkSNACKs` to `The Wasabi Wallet Developers`, you have to write:

```
Copyright (c) 2024 The Wasabi Wallet Developers
Copyright (c) 2024 GingerPrivacy
```

If you want, even if not required, you can also write:
```
Copyright (c) 2024 zkSNACKs
Copyright (c) 2024 The Wasabi Wallet Developers
Copyright (c) 2024 GingerPrivacy
```

However, removing `The Wasabi Wallet Developers` is a breach of MIT licensing and your repository might be taken down if a reclamation is made by a representative of `The Wasabi Wallet Developers`.

As such representative myself, I hereby invite you to respect `The Wasabi Wallet Developers` rights by including a mention to this entity in your `LICENSE.md` file

**Comment by drkgry** [comment]
Ok, will do it today.

**Comment by turbolay** [comment]
> Ok, will do it today, however you also removed zkSNACKs...

`zkSNACKs` is ceasing to exist and has transferred its intellectual property to `The Wasabi Wallet Developers`. Therefore, keeping its mention in the license is optional, and it is my understanding that they prefer their reference to be removed. I will add it back if requested.

However, you cannot remove the mention of `The Wasabi Wallet Developers`. You could keep the mention of `zkSNACKs` if you prefer not to mention `The Wasabi Wallet Developers`, but only if you stopped incorporating new code after the license was updated (which is not the case, as you cherry-picked several of my commits).

Similarly, in the Wasabi Wallet license, we would need to add a mention of `GingerPrivacy` if we incorporate some of your code.

**Comment by drkgry** [comment]
Checked it, you are right. Apologies.

**Comment by turbolay** [comment]
No problem at all !!

**Pull request merged**
